[tool.poetry]
name = "jg.plucker"
version = "0.0"
description = "Junior Guru scrapers"
authors = ["Honza Javorek <honza@junior.guru>"]
license = "AGPL-3.0-only"
readme = "README.md"
homepage = "https://junior.guru/"
repository = "https://github.com/juniorguru/plucker/"
packages = [{ include = "jg" }]

[tool.poetry.scripts]
plucker = "jg.plucker.cli:main"

[tool.poetry.dependencies]
python = "3.12.*"
apify = {version = "1.7.3b1", extras = ["scrapy"], allow-prereleases = true}
apify-client = {version = "1.6.5b2", allow-prereleases = true}
apify-shared = {version = "1.1.2", allow-prereleases = true}
click = "8.1.7"
extruct = "0.17.0"
feedparser = "6.0.11"
lxml = "5.3.0"
nest-asyncio = "1.6.0"
scrapy = "2.11.2"
scrapy-playwright = "0.0.41"

[tool.poetry.group.dev.dependencies]
cookiecutter = "2.6.0"
pytest = "8.3.3"
pytest-ruff = "0.4.1"
ruff = "0.6.*"

[tool.pytest.ini_options]
python_files = "test_*.py"
testpaths = "tests"
addopts = "--import-mode=importlib --ff --ruff --ruff-format"
filterwarnings = [
    "ignore:'cgi' is deprecated:DeprecationWarning",  # scrapy (twisted)
    "ignore:invalid escape sequence:DeprecationWarning",  # extruct
]

[tool.ruff]
target-version = "py311"
extend-exclude = ["scraper_template"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
combine-as-imports = true
lines-after-imports = 2

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
