[tool.poetry]
name = "juniorguru-plucker"
version = "0.0"
description = "Junior Guru scrapers"
authors = ["Honza Javorek <mail@honzajavorek.cz>"]
license = "MIT"
readme = "README.md"

# [tool.poetry.scripts]
# jgp = "juniorguru_plucker:__main__"

[tool.poetry.dependencies]
python = "3.11.*"
apify = {version = "1.5.0", extras = ["scrapy"]}
nest-asyncio = "1.5.8"
scrapy = "2.11.0"

[tool.poetry.group.dev.dependencies]
pytest = "7.4.4"
ruff = "0.1.11"

[tool.pytest.ini_options]
python_files = "test_*.py"
testpaths = "."
addopts = "--ff"
filterwarnings = [
    "ignore:'cgi' is deprecated:DeprecationWarning",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
