[tool.poetry]
name = "juniorguru-plucker"
version = "0.0"
description = "Junior Guru scrapers"
authors = ["Honza Javorek <mail@honzajavorek.cz>"]
license = "MIT"
readme = "README.md"

[tool.poetry.scripts]
jgp = "juniorguru_plucker.cli:main"

[tool.poetry.dependencies]
python = "3.11.*"
apify = {version = "1.5.0", extras = ["scrapy"]}
nest-asyncio = "1.5.9"
scrapy = "2.11.0"
click = "8.1.7"
markdown = "3.5.2"

[tool.poetry.group.dev.dependencies]
pytest = "7.4.4"
ruff = "0.1.11"
pytest-ruff = "0.2.1"

[tool.pytest.ini_options]
python_files = "test_*.py"
testpaths = "tests"
addopts = "--import-mode=importlib --ff --ruff --ruff-format"
filterwarnings = [
    "ignore:'cgi' is deprecated:DeprecationWarning",
]

[tool.ruff]
target-version = "py311"
extend-select = ["I"]

[tool.ruff.lint.isort]
combine-as-imports = true
lines-after-imports = 2

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
