[tool.poetry]
name = "juniorguru-plucker"
version = "0.0"
description = "Junior Guru scrapers"
authors = ["Honza Javorek <mail@honzajavorek.cz>"]
license = "MIT"
readme = "README.md"

# [tool.poetry.scripts]
# jgp = "juniorguru_plucker:__main__"

[tool.poetry.dependencies]
python = "3.11.*"
apify = {version = "1.4.1", extras = ["scrapy"]}
nest-asyncio = "1.5.8"
scrapy = "2.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
