[tool.poetry]
name = "jg.plucker"
version = "0.0"
description = "Junior Guru scrapers"
authors = ["Honza Javorek <honza@junior.guru>"]
license = "AGPL-3.0-only"
readme = "README.md"
homepage = "https://junior.guru/"
repository = "https://github.com/juniorguru/plucker/"
packages = [{ include = "jg" }]

[tool.poetry.scripts]
plucker = "jg.plucker.cli:main"

[tool.poetry.dependencies]
python = "3.12.*"
apify = { git = "https://github.com/apify/apify-sdk-python.git", branch = "master", extras = ["scrapy"] }
apify-client = "1.9.1"  # deployment of actors, monitoring, automation
apify-shared = "*"  # importing a few enums
click = "8.1.8"
diskcache = "5.6.3"
extruct = "0.18.0"
feedparser = "6.0.11"
ics = {version = "0.8.0.dev0", allow-prereleases = true}
linkedin-api = "2.3.1"
lxml = "5.3.0"
nest-asyncio = "1.6.0"
pydantic = "2.10.6"
scrapy = "2.12.0"
scrapy-impersonate = "1.4.1"
teemup = "1.2.1"

[tool.poetry.group.dev.dependencies]
cookiecutter = "2.6.0"
pytest = "8.3.4"
pytest-ruff = "0.4.1"
ruff = "0.9.*"

[tool.pytest.ini_options]
python_files = "test_*.py"
testpaths = "tests"
addopts = "--import-mode=importlib --ff --ruff --ruff-format"
filterwarnings = [
    "ignore:twisted.web.http.HTTPClient was deprecated:DeprecationWarning",  # scrapy
    "ignore:invalid escape sequence:SyntaxWarning",  # extruct
    "ignore:There is no current event loop:DeprecationWarning",  # apify
]

[tool.ruff]
target-version = "py312"
extend-exclude = ["scraper_template"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
combine-as-imports = true
lines-after-imports = 2

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
